"""Headless Abaqus Viewer ODB Visualization and Contour Rendering Engine.

Automates the generation and execution of headless off-screen postprocessing
scripts via `abaqus viewer -noGUI` to capture true finite element physical
field responses (e.g. von Mises stress concentrations, deformation displacement,
temperature gradients, contact sealing pressure) directly from authentic .odb
databases without needing interactive GUI windows or manual screenshotting.
"""

from dataclasses import dataclass
import os
from pathlib import Path
import subprocess
import sys
from typing import Any, Dict, List, Optional, Sequence, Union

from ..contracts.report import ReportFigure
from .batch import resolve_default_launcher


@dataclass
class ContourPlotRequest:
    """Specification for capturing an authentic finite element contour plot from an ODB."""

    output_filename: str
    variable_label: str = "S"
    component_or_invariant: Optional[str] = "Mises"
    output_position: str = "INTEGRATION_POINT"  # "INTEGRATION_POINT", "NODAL", "ELEMENT_NODAL"
    step_name: Optional[str] = None
    frame_index: int = -1
    plot_state: str = "CONTOURS_ON_DEF"  # "CONTOURS_ON_DEF", "CONTOURS_ON_UNDEF", "DEFORMED", "UNDEFORMED"
    view_orientation: str = "Iso"  # "Iso", "Front", "Back", "Top", "Bottom", "Left", "Right"
    deformation_scale_factor: Optional[float] = None  # None = AUTO, 1.0 = True scale
    caption: str = ""
    description: str = ""


def generate_headless_viewer_script(
    odb_path: Union[str, Path],
    requests: Sequence[ContourPlotRequest],
    output_dir: Optional[Union[str, Path]] = None,
) -> str:
    """Generate a clean, hardened Abaqus Viewer headless Python script.

    The script is designed to be executed via `abaqus viewer -noGUI <script.py>`
    and exports high-resolution PNG snapshots with off-screen rendering.
    """
    odb_str = Path(odb_path).as_posix()
    out_dir_str = Path(output_dir).as_posix() if output_dir else "."

    code_lines = [
        "# ===========================================================================",
        "# Auto-generated Headless Abaqus Viewer Postprocessing & Contour Script",
        "# Generated by abaqus_ai_agent for authentic CAE report generation",
        "# ===========================================================================",
        "import os",
        "import sys",
        "from abaqus import *",
        "from abaqusConstants import *",
        "import visualization",
        "",
        f"odb_path = r'{odb_str}'",
        f"out_dir = r'{out_dir_str}'",
        "if not os.path.exists(out_dir):",
        "    os.makedirs(out_dir)",
        "",
        "print('[HeadlessViewer] Opening ODB: %s' % odb_path)",
        "try:",
        "    odb = visualization.openOdb(path=odb_path, readOnly=True)",
        "except Exception as e:",
        "    print('[HeadlessViewer] ERROR: Failed to open ODB: %s' % e)",
        "    sys.exit(1)",
        "",
        "# Configure viewport and presentation options",
        "vp_name = session.currentViewportName",
        "vp = session.viewports[vp_name]",
        "vp.setValues(displayedObject=odb)",
        "",
        "# Publication-grade viewport settings: clean white background, shaded rendering",
        "session.printOptions.setValues(vpBackground=OFF)",
        "try:",
        "    vp.viewportAnnotationOptions.setValues(",
        "        triad=ON,",
        "        legend=ON,",
        "        title=OFF,",
        "        state=OFF,",
        "        annotations=OFF,",
        "    )",
        "    vp.odbDisplay.commonOptions.setValues(renderStyle=SHADED)",
        "except Exception:",
        "    pass",
        "",
    ]

    for idx, req in enumerate(requests):
        safe_fname = Path(req.output_filename).name
        target_path_expr = f"os.path.join(out_dir, r'{safe_fname}')"

        code_lines += [
            f"# ---------------------------------------------------------------------------",
            f"# Request {idx + 1}: {req.variable_label} ({req.component_or_invariant or 'Scalar'}) -> {safe_fname}",
            f"# ---------------------------------------------------------------------------",
            "try:",
            f"    # 1. Step & Frame selection",
        ]

        if req.step_name:
            code_lines.append(f"    if '{req.step_name}' in odb.steps:")
            code_lines.append(f"        target_step = odb.steps['{req.step_name}']")
            code_lines.append(f"        target_frame = target_step.frames[{req.frame_index}]")
            code_lines.append(f"        vp.odbDisplay.setFrame(step='{req.step_name}', frame={req.frame_index})")
        else:
            code_lines.append("    # Select final available step and frame")
            code_lines.append("    if len(odb.steps) > 0:")
            code_lines.append("        last_step_key = list(odb.steps.keys())[-1]")
            code_lines.append(f"        vp.odbDisplay.setFrame(step=last_step_key, frame={req.frame_index})")

        # Plot state
        p_state = req.plot_state
        code_lines += [
            "    # 2. Display mode (Contour on Deformed / Undeformed)",
            f"    vp.odbDisplay.display.setValues(plotState=({p_state},))",
        ]

        # Deformation scale factor
        if req.deformation_scale_factor is not None:
            code_lines.append(
                f"    vp.odbDisplay.commonOptions.setValues(deformationScaling=USER_SPECIFIED, uniformScaleFactor={float(req.deformation_scale_factor)})"
            )
        else:
            code_lines.append(
                "    vp.odbDisplay.commonOptions.setValues(deformationScaling=AUTO)"
            )

        # Primary Variable setup
        v_label = req.variable_label
        pos = req.output_position
        inv = req.component_or_invariant

        code_lines.append(f"    # 3. Field variable configuration: {v_label}")
        if inv:
            inv_upper = inv.upper()
            code_lines += [
                "    try:",
                f"        vp.odbDisplay.setPrimaryVariable(",
                f"            variableLabel='{v_label}',",
                f"            outputPosition={pos},",
                f"            refinement=(INVARIANT, '{inv_upper}')",
                "        )",
                "    except Exception:",
                "        try:",
                f"            vp.odbDisplay.setPrimaryVariable(",
                f"                variableLabel='{v_label}',",
                f"                outputPosition={pos},",
                f"                refinement=(INVARIANT, '{inv}')",
                "            )",
                "        except Exception:",
                "            try:",
                f"                vp.odbDisplay.setPrimaryVariable(",
                f"                    variableLabel='{v_label}',",
                f"                    outputPosition={pos},",
                f"                    refinement=(COMPONENT, '{inv}')",
                "                )",
                "            except Exception:",
                "                try:",
                f"                    vp.odbDisplay.setPrimaryVariable(",
                f"                        variableLabel='{v_label}',",
                f"                        outputPosition={pos},",
                f"                        refinement=(COMPONENT, '{inv_upper}')",
                "                    )",
                "                except Exception:",
                f"                    vp.odbDisplay.setPrimaryVariable(variableLabel='{v_label}', outputPosition={pos})",
            ]
        else:
            code_lines += [
                "    try:",
                f"        vp.odbDisplay.setPrimaryVariable(variableLabel='{v_label}', outputPosition={pos})",
                "    except Exception:",
                f"        vp.odbDisplay.setPrimaryVariable(variableLabel='{v_label}', outputPosition=NODAL)",
            ]

        # View Orientation
        v_orient = req.view_orientation
        code_lines += [
            f"    # 4. Camera view orientation: {v_orient}",
            f"    if '{v_orient}' in session.views:",
            f"        vp.view.setValues(session.views['{v_orient}'])",
            "    vp.view.fitView()",
            "",
            f"    # 5. Export authentic PNG",
            f"    out_img = {target_path_expr}",
            "    session.printToFile(fileName=out_img, format=PNG, canvasObjects=(vp,))",
            "    print('[HeadlessViewer] Successfully rendered: %s' % out_img)",
            "except Exception as err:",
            f"    print('[HeadlessViewer] ERROR: Failed to render {safe_fname}: %s' % err)",
            "    sys.exit(4)",
            "",
        ]

    code_lines += [
        "odb.close()",
        "print('[HeadlessViewer] Postprocessing completed successfully.')",
    ]

    return "\n".join(code_lines)


def render_odb_contours_headless(
    odb_path: Union[str, Path],
    requests: Sequence[ContourPlotRequest],
    output_dir: Union[str, Path],
    launcher: Optional[str] = None,
    timeout: int = 180,
) -> List[Path]:
    """Execute headless Abaqus Viewer to produce authentic physical contour images.

    Returns the list of generated PNG image Paths on disk.
    """
    odb = Path(odb_path).resolve()
    out_dir = Path(output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    script_path = out_dir / "_headless_viewer_post.py"
    script_content = generate_headless_viewer_script(
        odb_path=odb,
        requests=requests,
        output_dir=out_dir,
    )
    script_path.write_text(script_content, encoding="utf-8")

    resolved_launcher = resolve_default_launcher(launcher or "abaqus")
    if not (os.path.exists(resolved_launcher) or any(os.access(p, os.X_OK) for p in [resolved_launcher])):
        # Fallback check on PATH
        import shutil
        if not shutil.which(resolved_launcher):
            raise RuntimeError(
                f"Abaqus launcher not found at {resolved_launcher}. "
                "Headless viewer rendering requires authentic Abaqus installation."
            )

    cmd = [str(resolved_launcher), "viewer", "-noGUI", str(script_path)]
    use_shell = (os.name == "nt")

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(out_dir),
            capture_output=True,
            text=True,
            timeout=timeout,
            shell=use_shell,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(f"Headless Abaqus Viewer timed out after {timeout}s: {exc}")

    if proc.returncode != 0:
        err_msg = proc.stderr.strip() or proc.stdout.strip()
        raise RuntimeError(
            f"Headless Abaqus Viewer failed with exit code {proc.returncode}: {err_msg}"
        )

    # Collect successfully generated images
    produced = []
    for req in requests:
        target = out_dir / Path(req.output_filename).name
        if target.exists() and target.stat().st_size > 0:
            produced.append(target)

    # Clean up temporary script
    try:
        if script_path.exists():
            script_path.unlink()
    except Exception:
        pass

    return produced


def render_authentic_visualizations(
    odb_path: Union[str, Path],
    specs: Sequence[Any],
    output_dir: Union[str, Path],
    launcher: Optional[str] = None,
    timeout: int = 180,
    run_id: Optional[str] = None,
    input_hash: Optional[str] = None,
) -> List[ReportFigure]:
    """Authentically render and causally bind all requested CAE visualization specs.

    Fail-Closed Discipline:
    1. Validates that the target is a genuine binary ODB (never empty/mock).
    2. Translates each VisualizationSpec into a headless Abaqus Viewer contour request.
    3. Executes headless Abaqus Viewer.
    4. Ensures EVERY declared image is successfully produced on disk (> 0 bytes).
    5. Calculates authentic SHA-256 and causally binds run_id, input_hash, and odb_sha256 into the ReportFigure metadata.
    """
    import hashlib
    from .solver import is_authentic_binary_odb

    odb = Path(odb_path).resolve()
    if not odb.is_file():
        raise FileNotFoundError(f"Target ODB file does not exist: {odb}")
    if not is_authentic_binary_odb(odb):
        raise ValueError(
            f"Target file {odb} is not an authentic binary ODB. "
            "Headless viewer rendering strictly forbids synthetic or mock files."
        )

    h_odb = hashlib.sha256()
    with open(odb, "rb") as f:
        while chunk := f.read(65536):
            h_odb.update(chunk)
    odb_sha256 = h_odb.hexdigest()

    out_dir = Path(output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not specs:
        return []

    requests = []
    for spec in specs:
        v_orient = "Iso"
        vm = getattr(spec, "view_mode", "AUTO_FIT").upper()
        if "TOP" in vm:
            v_orient = "Top"
        elif "FRONT" in vm:
            v_orient = "Front"
        elif "SECTION" in vm or "ISOMETRIC" in vm:
            v_orient = "Iso"

        req = ContourPlotRequest(
            output_filename=spec.target_filename,
            variable_label=spec.field_name,
            component_or_invariant=spec.component,
            step_name=spec.step_name,
            frame_index=spec.frame_index,
            view_orientation=v_orient,
            caption=getattr(spec, "caption_zh", "") or getattr(spec, "caption_en", ""),
        )
        requests.append(req)

    render_odb_contours_headless(
        odb_path=odb,
        requests=requests,
        output_dir=out_dir,
        launcher=launcher,
        timeout=timeout,
    )

    figures: List[ReportFigure] = []
    for spec in specs:
        target_path = out_dir / Path(spec.target_filename).name
        if not target_path.exists() or target_path.stat().st_size == 0:
            raise FileNotFoundError(
                f"Fail-Closed: Authentic CAE visualization '{spec.target_filename}' "
                f"failed to render from ODB {odb}. Placeholder images are strictly forbidden."
            )

        h_img = hashlib.sha256()
        with open(target_path, "rb") as f:
            while chunk := f.read(65536):
                h_img.update(chunk)
        img_sha256 = h_img.hexdigest()

        fig = spec.to_report_figure(str(target_path))
        fig_meta = dict(fig.metadata or {})
        fig_meta["odb_path"] = str(odb)
        fig_meta["odb_sha256"] = odb_sha256
        fig_meta["image_sha256"] = img_sha256
        if run_id:
            fig_meta["run_id"] = run_id
        if input_hash:
            fig_meta["input_hash"] = input_hash

        bound_fig = ReportFigure(
            kind=fig.kind,
            path=fig.path,
            caption=fig.caption,
            source=fig.source,
            metadata=fig_meta,
        )
        figures.append(bound_fig)

    return figures
