# ===========================================================================
# Auto-generated Headless Abaqus Viewer Postprocessing & Contour Script
# Generated by abaqus_ai_agent for authentic CAE report generation
# ===========================================================================
import os
import sys
from abaqus import *
from abaqusConstants import *
import visualization

odb_path = r'D:/Vault/Abaqus/Abaqus-AI-Agent/test_assets/runs/case_03_manifold_run/Case_03_Exhaust_Manifold_Thermo_Mechanical/Step-2-CoupledOperation.odb'
out_dir = r'D:/Vault/Abaqus/Abaqus-AI-Agent/test_assets/runs/case_03_manifold_run/Case_03_Exhaust_Manifold_Thermo_Mechanical'
if not os.path.exists(out_dir):
    os.makedirs(out_dir)

print('[HeadlessViewer] Opening ODB: %s' % odb_path)
try:
    odb = visualization.openOdb(path=odb_path, readOnly=True)
except Exception as e:
    print('[HeadlessViewer] ERROR: Failed to open ODB: %s' % e)
    sys.exit(1)

# Configure viewport and presentation options
vp_name = session.currentViewportName
vp = session.viewports[vp_name]
vp.setValues(displayedObject=odb)

# Publication-grade viewport settings: clean white background, shaded rendering
session.printOptions.setValues(vpBackground=OFF)
try:
    vp.viewportAnnotationOptions.setValues(
        triad=ON,
        legend=ON,
        title=OFF,
        state=OFF,
        annotations=OFF,
    )
    vp.odbDisplay.commonOptions.setValues(renderStyle=SHADED)
except Exception:
    pass

# ---------------------------------------------------------------------------
# Request 1: S (Mises) -> case_03_manifold_mises_stress.png
# ---------------------------------------------------------------------------
try:
    # 1. Step & Frame selection
    if 'Hot_Coupled_Operation' in odb.steps:
        target_step = odb.steps['Hot_Coupled_Operation']
        target_frame = target_step.frames[-1]
        vp.odbDisplay.setFrame(step='Hot_Coupled_Operation', frame=-1)
    # 2. Display mode (Contour on Deformed / Undeformed)
    vp.odbDisplay.display.setValues(plotState=(CONTOURS_ON_DEF,))
    vp.odbDisplay.commonOptions.setValues(deformationScaling=AUTO)
    # 3. Field variable configuration: S
    try:
        vp.odbDisplay.setPrimaryVariable(
            variableLabel='S',
            outputPosition=INTEGRATION_POINT,
            refinement=(INVARIANT, 'MISES')
        )
    except Exception:
        try:
            vp.odbDisplay.setPrimaryVariable(
                variableLabel='S',
                outputPosition=INTEGRATION_POINT,
                refinement=(INVARIANT, 'Mises')
            )
        except Exception:
            try:
                vp.odbDisplay.setPrimaryVariable(
                    variableLabel='S',
                    outputPosition=INTEGRATION_POINT,
                    refinement=(COMPONENT, 'Mises')
                )
            except Exception:
                try:
                    vp.odbDisplay.setPrimaryVariable(
                        variableLabel='S',
                        outputPosition=INTEGRATION_POINT,
                        refinement=(COMPONENT, 'MISES')
                    )
                except Exception:
                    vp.odbDisplay.setPrimaryVariable(variableLabel='S', outputPosition=INTEGRATION_POINT)
    # 4. Camera view orientation: Iso
    if 'Iso' in session.views:
        vp.view.setValues(session.views['Iso'])
    vp.view.fitView()

    # 5. Export authentic PNG
    out_img = os.path.join(out_dir, r'case_03_manifold_mises_stress.png')
    session.printToFile(fileName=out_img, format=PNG, canvasObjects=(vp,))
    print('[HeadlessViewer] Successfully rendered: %s' % out_img)
except Exception as err:
    print('[HeadlessViewer] WARNING: Failed to render case_03_manifold_mises_stress.png: %s' % err)

# ---------------------------------------------------------------------------
# Request 2: U (Magnitude) -> case_03_manifold_displacement.png
# ---------------------------------------------------------------------------
try:
    # 1. Step & Frame selection
    if 'Hot_Coupled_Operation' in odb.steps:
        target_step = odb.steps['Hot_Coupled_Operation']
        target_frame = target_step.frames[-1]
        vp.odbDisplay.setFrame(step='Hot_Coupled_Operation', frame=-1)
    # 2. Display mode (Contour on Deformed / Undeformed)
    vp.odbDisplay.display.setValues(plotState=(CONTOURS_ON_DEF,))
    vp.odbDisplay.commonOptions.setValues(deformationScaling=USER_SPECIFIED, uniformScaleFactor=5.0)
    # 3. Field variable configuration: U
    try:
        vp.odbDisplay.setPrimaryVariable(
            variableLabel='U',
            outputPosition=NODAL,
            refinement=(INVARIANT, 'MAGNITUDE')
        )
    except Exception:
        try:
            vp.odbDisplay.setPrimaryVariable(
                variableLabel='U',
                outputPosition=NODAL,
                refinement=(INVARIANT, 'Magnitude')
            )
        except Exception:
            try:
                vp.odbDisplay.setPrimaryVariable(
                    variableLabel='U',
                    outputPosition=NODAL,
                    refinement=(COMPONENT, 'Magnitude')
                )
            except Exception:
                try:
                    vp.odbDisplay.setPrimaryVariable(
                        variableLabel='U',
                        outputPosition=NODAL,
                        refinement=(COMPONENT, 'MAGNITUDE')
                    )
                except Exception:
                    vp.odbDisplay.setPrimaryVariable(variableLabel='U', outputPosition=NODAL)
    # 4. Camera view orientation: Iso
    if 'Iso' in session.views:
        vp.view.setValues(session.views['Iso'])
    vp.view.fitView()

    # 5. Export authentic PNG
    out_img = os.path.join(out_dir, r'case_03_manifold_displacement.png')
    session.printToFile(fileName=out_img, format=PNG, canvasObjects=(vp,))
    print('[HeadlessViewer] Successfully rendered: %s' % out_img)
except Exception as err:
    print('[HeadlessViewer] WARNING: Failed to render case_03_manifold_displacement.png: %s' % err)

# ---------------------------------------------------------------------------
# Request 3: NT (NT11) -> case_03_manifold_temperature.png
# ---------------------------------------------------------------------------
try:
    # 1. Step & Frame selection
    if 'Steady_Heat_Transfer' in odb.steps:
        target_step = odb.steps['Steady_Heat_Transfer']
        target_frame = target_step.frames[-1]
        vp.odbDisplay.setFrame(step='Steady_Heat_Transfer', frame=-1)
    # 2. Display mode (Contour on Deformed / Undeformed)
    vp.odbDisplay.display.setValues(plotState=(CONTOURS_ON_DEF,))
    vp.odbDisplay.commonOptions.setValues(deformationScaling=AUTO)
    # 3. Field variable configuration: NT
    try:
        vp.odbDisplay.setPrimaryVariable(
            variableLabel='NT',
            outputPosition=NODAL,
            refinement=(INVARIANT, 'NT11')
        )
    except Exception:
        try:
            vp.odbDisplay.setPrimaryVariable(
                variableLabel='NT',
                outputPosition=NODAL,
                refinement=(INVARIANT, 'NT11')
            )
        except Exception:
            try:
                vp.odbDisplay.setPrimaryVariable(
                    variableLabel='NT',
                    outputPosition=NODAL,
                    refinement=(COMPONENT, 'NT11')
                )
            except Exception:
                try:
                    vp.odbDisplay.setPrimaryVariable(
                        variableLabel='NT',
                        outputPosition=NODAL,
                        refinement=(COMPONENT, 'NT11')
                    )
                except Exception:
                    vp.odbDisplay.setPrimaryVariable(variableLabel='NT', outputPosition=NODAL)
    # 4. Camera view orientation: Iso
    if 'Iso' in session.views:
        vp.view.setValues(session.views['Iso'])
    vp.view.fitView()

    # 5. Export authentic PNG
    out_img = os.path.join(out_dir, r'case_03_manifold_temperature.png')
    session.printToFile(fileName=out_img, format=PNG, canvasObjects=(vp,))
    print('[HeadlessViewer] Successfully rendered: %s' % out_img)
except Exception as err:
    print('[HeadlessViewer] WARNING: Failed to render case_03_manifold_temperature.png: %s' % err)

# ---------------------------------------------------------------------------
# Request 4: CPRESS (Scalar) -> case_03_manifold_contact_pressure.png
# ---------------------------------------------------------------------------
try:
    # 1. Step & Frame selection
    if 'Hot_Coupled_Operation' in odb.steps:
        target_step = odb.steps['Hot_Coupled_Operation']
        target_frame = target_step.frames[-1]
        vp.odbDisplay.setFrame(step='Hot_Coupled_Operation', frame=-1)
    # 2. Display mode (Contour on Deformed / Undeformed)
    vp.odbDisplay.display.setValues(plotState=(CONTOURS_ON_DEF,))
    vp.odbDisplay.commonOptions.setValues(deformationScaling=AUTO)
    # 3. Field variable configuration: CPRESS
    try:
        vp.odbDisplay.setPrimaryVariable(variableLabel='CPRESS', outputPosition=NODAL)
    except Exception:
        vp.odbDisplay.setPrimaryVariable(variableLabel='CPRESS', outputPosition=NODAL)
    # 4. Camera view orientation: Top
    if 'Top' in session.views:
        vp.view.setValues(session.views['Top'])
    vp.view.fitView()

    # 5. Export authentic PNG
    out_img = os.path.join(out_dir, r'case_03_manifold_contact_pressure.png')
    session.printToFile(fileName=out_img, format=PNG, canvasObjects=(vp,))
    print('[HeadlessViewer] Successfully rendered: %s' % out_img)
except Exception as err:
    print('[HeadlessViewer] WARNING: Failed to render case_03_manifold_contact_pressure.png: %s' % err)

odb.close()
print('[HeadlessViewer] Postprocessing completed successfully.')